# Generated by Django 4.0.3 on 2022-04-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_context_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='date_posted',
        ),
    ]
